### ISSUE TITLE
Locate Viable Sources for Information

### ISSUE THREAD

**Issue by 0xADD1E** [0xADD1E/Databases-Project#7]
As a user, I want this application to actually show information.

To do that, we of course need data on this. That data, in turn, must come from somewhere. 

Acceptance Criteria:
- Potential sources for information in all tables located and documented within this issue
	- Optionally, download the information, and begin looking into how it might be transformed into the appropriate form

**Comment by nonsix** [comment]
So I have media like photos and sounds of each pokemon. If that is something we want to be committed let me know.
